# editing / UI
ble-face -s region                    "bg={{colors.secondary_container.default.hex}},fg={{colors.on_secondary_container.default.hex}}"
ble-face -s region_target             "bg={{colors.primary_container.default.hex}},fg={{colors.on_primary_container.default.hex}}"
ble-face -s region_match              "bg={{colors.tertiary_container.default.hex}},fg={{colors.on_tertiary_container.default.hex}}"
ble-face -s region_insert             "bg={{colors.secondary_container.default.hex}},fg={{colors.on_secondary_container.default.hex}}"
ble-face -s disabled                  "fg={{colors.outline.default.hex}}"
ble-face -s overwrite_mode            "bg={{colors.primary_container.default.hex}},fg={{colors.on_primary_container.default.hex}}"
ble-face -s vbell                     "reverse"
ble-face -s vbell_erase               "bg={{colors.surface_variant.default.hex}}"
ble-face -s vbell_flash               "fg={{dank16.color1.default.hex}},reverse"
ble-face -s prompt_status_line        "fg={{colors.on_surface.default.hex}},bg={{colors.surface_variant.default.hex}}"

# syntax highlighting
ble-face -s syntax_default            "fg={{dank16.color7.default.hex}}"
ble-face -s syntax_command            "fg={{dank16.color4.default.hex}},bold"
ble-face -s syntax_quoted             "fg={{dank16.color2.default.hex}}"
ble-face -s syntax_quotation          "fg={{dank16.color2.default.hex}},bold"
ble-face -s syntax_escape             "fg={{dank16.color6.default.hex}}"
ble-face -s syntax_expr               "fg={{dank16.color5.default.hex}}"
ble-face -s syntax_error              "bg={{dank16.color1.default.hex}},fg={{dank16.color0.default.hex}},bold"
ble-face -s syntax_varname            "fg={{dank16.color4.default.hex}},bold"
ble-face -s syntax_param_expansion    "fg={{dank16.color6.default.hex}},bold"
ble-face -s syntax_delimiter          "fg={{dank16.color8.default.hex}},bold"
ble-face -s syntax_history_expansion  "bg={{dank16.color3.default.hex}},fg={{dank16.color0.default.hex}}"
ble-face -s syntax_function_name      "fg={{dank16.color4.default.hex}},bold"
ble-face -s syntax_comment            "fg={{dank16.color8.default.hex}}"
ble-face -s syntax_glob               "fg={{dank16.color3.default.hex}},bold"
ble-face -s syntax_brace              "fg={{dank16.color6.default.hex}},bold"
ble-face -s syntax_tilde              "fg={{dank16.color6.default.hex}},bold"
ble-face -s syntax_document           "fg={{dank16.color3.default.hex}}"
ble-face -s syntax_document_begin     "fg={{dank16.color3.default.hex}},bold"

# command classes
ble-face -s command_builtin_dot       "fg={{dank16.color4.default.hex}},bold"
ble-face -s command_builtin           "fg={{dank16.color4.default.hex}}"
ble-face -s command_alias             "fg={{dank16.color6.default.hex}}"
ble-face -s command_function          "fg={{dank16.color4.default.hex}},bold"
ble-face -s command_file              "fg={{dank16.color2.default.hex}},bold"
ble-face -s command_keyword           "fg={{dank16.color5.default.hex}},bold"
ble-face -s command_jobs              "fg={{dank16.color6.default.hex}}"
ble-face -s command_directory         "fg={{dank16.color4.default.hex}},underline"
ble-face -s command_suffix            "bg={{dank16.color2.default.hex}},fg={{dank16.color0.default.hex}}"
ble-face -s command_suffix_new        "bg={{dank16.color1.default.hex}},fg={{dank16.color0.default.hex}}"

# filenames / paths
ble-face -s filename_directory        "underline,fg={{dank16.color4.default.hex}}"
ble-face -s filename_directory_sticky "underline,bg={{dank16.color4.default.hex}},fg={{dank16.color0.default.hex}}"
ble-face -s filename_link             "underline,fg={{dank16.color6.default.hex}}"
ble-face -s filename_orphan           "underline,fg={{dank16.color1.default.hex}}"
ble-face -s filename_executable       "underline,fg={{dank16.color2.default.hex}},bold"
ble-face -s filename_setuid           "underline,bg={{dank16.color1.default.hex}},fg={{dank16.color0.default.hex}}"
ble-face -s filename_setgid           "underline,bg={{dank16.color3.default.hex}},fg={{dank16.color0.default.hex}}"
ble-face -s filename_other            "underline,fg={{dank16.color7.default.hex}}"
ble-face -s filename_socket           "underline,fg={{dank16.color6.default.hex}}"
ble-face -s filename_pipe             "underline,fg={{dank16.color2.default.hex}}"
ble-face -s filename_character        "underline,fg={{dank16.color9.default.hex}}"
ble-face -s filename_block            "underline,fg={{dank16.color9.default.hex}}"
ble-face -s filename_warning          "underline,fg={{dank16.color1.default.hex}},bold"
ble-face -s filename_url              "underline,fg={{dank16.color4.default.hex}}"
ble-face -s filename_ls_colors        "underline"

# variable classes
ble-face -s varname_export            "fg={{dank16.color4.default.hex}},bold"
ble-face -s varname_expr              "fg={{dank16.color5.default.hex}},bold"
ble-face -s varname_array             "fg={{dank16.color5.default.hex}},bold"
ble-face -s varname_hash              "fg={{dank16.color6.default.hex}},bold"
ble-face -s varname_transform         "fg={{dank16.color6.default.hex}},bold"
ble-face -s varname_readonly          "fg={{dank16.color3.default.hex}},bold"
ble-face -s varname_new               "fg={{dank16.color2.default.hex}}"
ble-face -s varname_unset             "fg={{dank16.color8.default.hex}}"
ble-face -s varname_empty             "fg={{dank16.color8.default.hex}}"
ble-face -s varname_number            "fg={{dank16.color3.default.hex}}"

# arguments
ble-face -s argument_option           "fg={{dank16.color12.default.hex}},bold"
ble-face -s argument_error            "bg={{dank16.color1.default.hex}},fg={{dank16.color0.default.hex}},bold"

# completions / suggestions UI
ble-face -s auto_complete             "fg={{colors.outline.default.hex}}"
ble-face -s menu_complete_match       "bold"
ble-face -s menu_complete_selected    "reverse"
ble-face -s menu_desc_default         "none"
ble-face -s menu_desc_type            "ref:syntax_delimiter"
ble-face -s menu_desc_quote           "ref:syntax_quoted"
ble-face -s menu_filter_fixed         "bold"
ble-face -s menu_filter_input         "bg={{colors.tertiary_container.default.hex}},fg={{colors.on_tertiary_container.default.hex}}"
