--color=fg:{{colors.on_background.default.hex}},hl:{{colors.tertiary.default.hex}}
--color=fg+:{{colors.on_surface.default.hex}},bg+:{{colors.surface_variant.default.hex}},gutter:{{colors.surface_variant.default.hex}},hl+:{{colors.tertiary.default.hex}}
--color=info:{{colors.primary.default.hex}}
--color=border:{{colors.primary.default.hex}},scrollbar:{{colors.outline_variant.default.hex}},preview-border:{{colors.secondary.default.hex}},preview-scrollbar:{{colors.outline_variant.default.hex}}
--color=label:{{colors.secondary.default.hex}}
--color=prompt:{{colors.tertiary.default.hex}},pointer:{{colors.tertiary.default.hex}},marker:{{colors.error.default.hex}},spinner:{{colors.tertiary.default.hex}},header:{{colors.tertiary.default.hex}}
