# Matugen-generated palette
[palettes.gen]
os_bg     = '{{colors.primary.default.hex}}'
dir_bg    = '{{colors.secondary.default.hex}}'
git_bg    = '{{colors.tertiary.default.hex}}'
lang_bg   = '{{colors.surface.default.hex}}'
status_bg = '{{colors.surface_variant.default.hex}}'

on_os     = '{{colors.on_primary.default.hex}}'
on_dir    = '{{colors.on_secondary.default.hex}}'
on_git    = '{{colors.on_tertiary.default.hex}}'
on_lang   = '{{colors.on_surface.default.hex}}'
on_status = '{{colors.on_surface_variant.default.hex}}'

success   = '{{colors.primary.default.hex}}'
error     = '{{colors.error.default.hex}}'
warning   = '{{colors.secondary.default.hex}}'
