# Prompt
format = """
[](nord10)\
$os\
$username\
$hostname\
[](bg:nord9 fg:nord10)\
$directory\
[](bg:nord8 fg:nord9)\
$git_branch\
$git_status\
[](bg:nord7 fg:nord8)\
$c\
$python\
$haskell\
$java\
$rust\
[](bg:nord15 fg:nord7)\
$status\
[](fg:nord15)
$character
"""
scan_timeout = 50
command_timeout = 500
add_newline = true
palette = 'nord'


# Custom palletes
[palettes.nord]
nord0 = '#2E3440'
nord1 = '#3B4252'
nord2 = '#434C5E'
nord3 = '#4C566A'
nord4 = '#D8DEE9'
nord5 = '#E5E9F0'
nord6 = '#ECEFF4'
nord7 = '#8FBCBB'
nord8 = '#88C0D0'
nord9 = '#81A1C1'
nord10 = '#5E81AC'
nord11 = '#BF616A'
nord12 = '#D08770'
nord13 = '#EBCB8B'
nord14 = '#A2BE8A'
nord15 = '#B48EAD'


# OS, username, and hostname 
[os]
format = '[$symbol ]($style)'
style = 'bg:nord10 fg:nord6'
disabled = false

[username]
format = '[$user ]($style)'
style_root = 'bg:nord0 fg:nord11'
style_user = 'bg:nord10 fg:nord6'
show_always = true
disabled = false

[hostname]
format = '[$hostname $ssh_symbol ]($style)'
style = 'bg:nord10 fg:nord6'
ssh_symbol = ' '
ssh_only = true
trim_at = '.'
disabled = false


# Directory
[directory]
format = '[ $path ]($style)[$read_only]($read_only_style)'
style = 'bg:nord9 fg:nord6'
read_only_style = 'bg:nord9 fg:nord13'
read_only = '󰌱 '
truncation_length = 2
truncation_symbol = '.../'
truncate_to_repo = true
use_os_path_sep = true
disabled = false


# Git
[git_branch]
format = '[ $symbol $branch ]($style)'
style = 'bg:nord8 fg:nord6'
symbol = ' '
truncation_length = 50
truncation_symbol = '...'

[git_status]
format = '[(| $ahead_behind )(| $conflicted )(| $staged$modified$deleted$renamed$typechanged )(| $stashed )]($style)'
style = 'bg:nord8 fg:nord6'
ahead = '⇡ ${count}'
diverged = '⇕ ⇡ ${ahead_count}⇣ ${behind_count}'
behind = '⇣ ${count}'
up_to_date = ' '
conflicted = '[󱚞 ](bg:nord8 fg:nord12)'
staged = '󰴥 '
modified = ' '
deleted = ' '
renamed = ' '
typechanged = ' '
stashed = ''


# Programming
[c]
symbol = ' '
style = 'bg:nord7 fg:nord6'
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ' '
style = 'bg:nord7 fg:nord6'
format = '[ $symbol ($version) (\($virtualenv\)) ]($style)'

[gradle]
style = 'bg:nord7 fg:nord6'
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = ' '
style = 'bg:nord7 fg:nord6'
format = '[ $symbol ($version) ]($style)'

[java]
symbol = ' '
style = 'bg:nord7 fg:nord6'
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ''
style = 'bg:nord7 fg:nord6'
format = '[ $symbol ($version) ]($style)'


# Status
[status]
format = '[ $symbol$status( \(ERR: $common_meaning\))( \(SIG: $signal_name\)) ]($style)'
style = "bg:nord15 fg:nord6"
success_symbol = ''
symbol = '[󰯆 ](bg:nord15 fg:nord11)'
not_executable_symbol = '[ ](bg:nord15 fg:nord11)'
not_found_symbol = '[ ](bg:nord15 fg:nord11)'
sigint_symbol = '[󱐋](bg:nord15 fg:nord13)'
signal_symbol = '[󱐋](bg:nord15 fg:nord12)'
recognize_signal_code = true
map_symbol = true
disabled = false


# Character (pre-input)
[character]
format = ' $symbol '
success_symbol = '[󱞩](fg:nord14)'
error_symbol = '[󱞩](fg:nord11)'
disabled = false


 
# Miscellaneous
[os.symbols]
Alpaquita = ' '
Alpine = ' '
Amazon = ' '
Android = ' '
Arch = ' '
Artix = ' '
CentOS = ' '
Debian = ' '
DragonFly = ' '
Emscripten = ' '
EndeavourOS = ' '
Fedora = ' '
FreeBSD = ' '
Garuda = '󰛓 '
Gentoo = ' '
HardenedBSD = '󰞌 '
Illumos = '󰈸 '
Linux = ' '
Mabox = ' '
Macos = ' '
Manjaro = ' '
Mariner = ' '
MidnightBSD = ' '
Mint = ' '
NetBSD = ' '
NixOS = ' '
OpenBSD = '󰈺 '
openSUSE = ' '
OracleLinux = '󰌷 '
Pop = ' '
Raspbian = ' '
Redhat = ' '
RedHatEnterprise = ' '
Redox = '󰀘 '
Solus = '󰠳 '
SUSE = ' '
Ubuntu = ' '
Unknown = ' '
Windows = '󰍲 '
