idle_bg = "#3b4252"
idle_fg = "#d8dee9"
info_bg = "#3b4252"
info_fg = "#e5e9f0"
good_bg = "#3b4252"
good_fg = "#a3be8c"
warning_bg = "#3b4252"
warning_fg = "#d08770"
critical_bg = "#3b4252"
critical_fg = "#bf616a"
#separator = "\ue216"
separator = " "
separator_bg = "auto"
separator_fg = "#4c566a"
start_separator = ""
end_separator = ""
