# Fonts
font_family      family='Iosevka Term' style=SemiBold
bold_font        family='Iosevka Term' style=ExtraBold
italic_font      family='Iosevka Term' style='SemiBold Italic'
bold_italic_font family='Iosevka Term' style='ExtraBold Italic'
font_size 14.0

symbol_map U+23FB-U+23FE,U+2B58,U+E000-U+E00A,U+E0A0-U+E0A3,U+E0B0-U+E0C8,U+E0CA,U+E0CC-U+E0D7,U+E200-U+E2A9,U+E300-U+E3E3,U+E5FA-U+E6B7,U+E700-U+E8EF,U+EA60-U+EC1E,U+ED00-U+EFCE,U+EE00-U+EE0B,U+F000-U+F2FF,U+F300-U+F381,U+F400-U+F533,U+F0001-U+F1AF0 Symbols Nerd Font Mono

# Window
window_padding_width 4
hide_window_decorations yes
background_opacity 1
background_blur 32

# Cursor
cursor_shape underline
cursor_shape_unfocused underline
cursor_blink_interval -1

# Scrolling
scrollback_lines 5000
scrollbar scrolled-and-hovered

# Shell integration
shell_integration no-cursor

# System
copy_on_select yes
clear_selection_on_clipboard_loss yes
strip_trailing_spaces smart
focus_folows_mouse yes
enable_audio_bell false
notify_on_cmd_finish invisible 10.0

# Key bindings
include bindings.conf

# Tabs and colors
include tabs.conf
include colors.conf
