# Fonts
font_family      family='IosevkaTerm Nerd Font' style=SemiBold
bold_font        family='IosevkaTerm Nerd Font' style=ExtraBold
italic_font      family='IosevkaTerm Nerd Font' style='SemiBold Italic'
bold_italic_font family='IosevkaTerm Nerd Font' style='ExtraBold Italic'
font_size 14.0

# Window
window_padding_width 4
hide_window_decorations yes
background_opacity 1
background_blur 32

# Cursor
cursor_shape underline
cursor_shape_unfocused underline
cursor_blink_interval -1

# Scrolling
scrollback_lines 5000
scrollbar scrolled-and-hovered

# Shell integration
shell_integration no-cursor

# System
copy_on_select yes
clear_selection_on_clipboard_loss yes
strip_trailing_spaces smart
focus_folows_mouse yes
enable_audio_bell false
notify_on_cmd_finish invisible 10.0

# Key bindings
include bindings.conf

# Tabs and colors
include tabs.conf
include colors.conf
