#!/bin/sh

# Source .xprofile
if [ -f "$XDG_CONFIG_HOME/X11/.xprofile" ]; then
    . "$XDG_CONFIG_HOME/X11/.xprofile"
fi

# User-specific X resources
usrsrcs="$XDG_CONFIG_HOME/X11/.Xresources"

# Merge in user resources
if [ -f "$usrsrcs" ]; then
    xrdb -merge -I${XDG_CONFIG_HOME}/X11 "$usrsrcs"
fi
