#!/bin/sh

# Source .xprofile
if [ -f "$XDG_CONFIG_HOME/X11/.xprofile" ]; then
    . "$XDG_CONFIG_HOME/X11/.xprofile"
fi

# User-specific X resources
userresources="$XDG_CONFIG_HOME/X11/.Xresources"

# Merge in user resources
if [ -f "$userresources" ]; then
    xrdb -load -I${XDG_CONFIG_HOME}/X11 -merge "$userresources"
fi
