[terminal]
# The VT to run the greeter on. Can be "next", "current" or a number designating the VT.
vt = 1
switch = true


[general]
source_profile = true
runfile = "/run/greetd.run"


# The default session, also known as the greeter.
[default_session]
# The command to run
command = "tuigreet --cmd startx --theme 'border=cyan;text=white;prompt=green;time=white;action=yellow;button=yellow;container=black' --time --time-format '%a %d %b %Y %T' --greeting 'Welcome' --greet-align center --asterisks --remember --power-shutdown '/sbin/systemctl poweroff' --power-reboot '/sbin/systemctl reboot'"

# The user to run the command as. The privileges this user must have depends on the greeter.
# A graphical greeter may for example require the user to be in the `video` group.
user = "greeter"
