fd --gen-completions bash
fd --gen-completions bash
--color=fg:#e5e9f0,hl:#ebcb8b
--color=fg+:#eceff4,bg+:#434c5e,gutter:#434c5e,hl+:#ebcb8b
--color=info:#a3be8c
--color=border:#5e81ac,scrollbar:#d8dee9,preview-border:#81a1c1,preview-scrollbar:#d8dee9
--color=label:#8fbcbb
--color=prompt:#b48ead,pointer:#b48ead,marker:#d08770,spinner:#ebcb8b,header:#ebcb8b
