[general]
import = ["~/.config/alacritty/alacritty-colors-nord.toml"]


[env]
TERM="alacritty"


[window]
blur = true
opacity = 0.9
class = { instance = "Alacritty", general = "Terminal"}


[scrolling]
history = 25000
multiplier = 3


[font]
#normal = { family = "Iosevka Nerd Font", style = "SemiBold"}
#size = 12
normal = { family = "MonaspiceKr Nerd Font", style = "Medium"}
size = 11
bold = { style = "Bold" }
italic = { style = "Medium Italic"}
bold_italic = { style = "Bold Italic"}
builtin_box_drawing = true


[cursor]
style = { shape = "Block", blinking = "Off" }
vi_mode_style = "None"
#blink_interval = 500
#blink_timeout = 5
unfocused_hollow = true
thickness = 0.15


[terminal]
shell = { program = "/usr/bin/zsh" }


[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "O", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"


[keyboard]
bindings = [
    # Movement/Navigation
    { key = "K", mods = "Control", mode = "~Alt", action = "ScrollLineUp" },
    { key = "J", mods = "Control", mode = "~Alt", action = "ScrollLineDown" },
    { key = "Up", mods = "Control", mode = "~Alt", action = "ScrollHalfPageUp" },
    { key = "Down", mods = "Control", mode = "~Alt", action = "ScrollHalfPageDown" },
    { key = "PageUp", mods = "Control", mode = "~Alt", action = "ScrollPageUp" },
    { key = "PageDown", mods = "Control", mode = "~Alt", action = "ScrollPageDown" },
    { key = "Home", mods = "Control", mode = "~Alt", action = "ScrollToTop" },
    { key = "End", mods = "Control", mode = "~Alt", action = "ScrollToBottom" },

    # Searching
    { key = "S", mods = "Control", mode = "~Search|~Alt", action = "SearchForward" },
    { key = "S", mods = "Control", mode = "Search", action = "SearchFocusNext" },
    { key = "R", mods = "Control", mode = "~Search|~Alt", action = "SearchBackward" },
    { key = "R", mods = "Control", mode = "Search", action = "SearchFocusNext" },    
    { key = "G", mods = "Control", mode = "Search", action = "SearchCancel" },
    
    
    # Unset defaults
    { key = "PageUp", mods = "Shift", mode = "~Alt", action = "ReceiveChar" },
    { key = "PageDown", mods = "Shift", mode = "~Alt", action = "ReceiveChar" },
    { key = "Home", mods = "Shift", mode = "~Alt", action = "ReceiveChar" },
    { key = "End", mods = "Shift", mode = "~Alt", action = "ReceiveChar" },
]
