#+TITLE: Matthias's Literate Emacs Configuration
#+AUTHOR: Matthias Meijers
#+EMAIL: kernel@mmeijers.com
#+LANGUAGE: en
#+STARTUP: content
#+PROPERTY: header-args:emacs-lisp :results none :tangle init-test.el :mkdirp yes 

Literate configuration for my Emacs. Beyond reasoning and explanations for the
individual settings and configurations, also includes information on external
dependencies and links to official (external) documentation where relevant.

* Overview
** Produced files
Tangling this file (with [[https://orgmode.org/manual/Extracting-Source-Code.html#index-org_002dbabel_002dtangle][org-babel-tangle]]) produces both an [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Early-Init-File.html][early
initialization file (early-init.el)]] and a [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Init-File.html][regular initialization file
(init.el)]] in the same directory as this file resides in.
- [[id:4c1ec44b-b1e3-4119-a293-e92b94145111][Early initialization customization]]
- [[id:43b929ca-f602-4d36-9b4e-ed056e2fdb58][Regular initialization customization]] 
** Naming conventions
For clarity, and in an attempt to minimize name clashes, we try to adhere to the
following naming conventions:
- Constant (self-defined) identifiers are typeset in all capitals, with
  (sub)words separated by an underscore.
- Variables and functions (self-defined) identifiers start with either =a-= or
  =an-= (as in, the English articles), and otherwise try to follow standard
  Emacs conventions.
** Recommended workflow
- Edit this file
- Execute =org-babel-tangle= (with this file as target)
- Restart Emacs
** Official documentation
- [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Startup-Summary.html][Emacs's startup summary]]
- [[https://orgmode.org/manual/Extracting-Source-Code.html][Extracting source code with Org]]

* Early initialization (early-init.el)
:PROPERTIES:
:ID:       4c1ec44b-b1e3-4119-a293-e92b94145111
:header-args:emacs-lisp: :tangle early-init-test.el
:END:
[[https://www.gnu.org/software/emacs/manual/html_node/emacs/Early-Init-File.html][The early initialization file]] contains customization and configuration that is
executed before Emacs has (1) fully initialized the GUI and (2)
enabled/activated packages. While configuration that must be executed this early
during startup is definitely put here, we may also put (some) configuration here
that we feel fits better here, whether that be conceptually or practically.
** Header
To ensure the buffer/file is evaluated using [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Selecting-Lisp-Dialect.html][modern Lisp dialect with lexical binding
(instead of dynamic)]], we set [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Selecting-Lisp-Dialect.html#index-lexical_002dbinding][lexical-binding]] (to `t') as a [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Specifying-File-Variables.html][file-local variable
in the first line of the file header]].
#+begin_src emacs-lisp
  ;; -*- lexical-binding: t; -*-
  ;; early-init.el
#+end_src
** Native compilation
[[https://www.gnu.org/software/emacs/manual/html_node/elisp/Native-Compilation.html][Native compilation]] compiles files/functions to native code (for the considered
platform), increasing performance compared to byte code or, even worse,
interpreted code. To promote and smoothen the compilation process, we allow
asynchronous native compilation of loaded files when needed
([[https://www.gnu.org/software/emacs/manual/html_node/elisp/Native_002dCompilation-Variables.html#index-native_002dcomp_002djit_002dcompilation][native-comp-jit-compilation]]), have Emacs double-check with us before shutting
down when compilation is still running ([[https://www.gnu.org/software/emacs/manual/html_node/elisp/Native_002dCompilation-Variables.html#index-native_002dcomp_002dasync_002dquery_002don_002dexit][native-comp-async-query-on-exit]]), and
natively compile packages as part of their installation
(package-native-compile).
#+begin_src emacs-lisp
  ;; Native compilation
  (setopt native-comp-jit-compilation t)
  (setopt native-comp-async-query-on-exit t)
  (setopt package-native-compile t)
#+end_src
** File loading
When Emacs [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Lisp-Libraries.html][loads a file]], we want it to load the newest when there are multiple possible
versions/variants ([[https://doc.endlessparentheses.com/Var/load-prefer-newer.html][load-prefer-newer]]).
#+begin_src emacs-lisp
  ;; File loading
  (setopt load-prefer-newer t)
#+end_src
** Garbage collection
With the default settings, [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Garbage-Collection.html][Emacs's garbage collection]] can run quite frequently.
To remedy this, we increase the thresholds at which Emacs decides to start
garbage collection ([[https://www.gnu.org/software/emacs/manual/html_node/elisp/Garbage-Collection.html#index-gc_002dcons_002dthreshold][gc-cons-threshold]] and [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Garbage-Collection.html#index-gc_002dcons_002dpercentage][gc-cons-percentage]]); the actual
values are loosely based on recommendations (e.g., from [[https://emacsconf.org/2023/talks/gc/][this talk around ~25:00]])
and some own testing. Adjustments might be desirable for different setups.
#+begin_src emacs-lisp
  ;; Garbage collection
  (setopt gc-cons-threshold 33554432
          gc-cons-percentage 0.15)
#+end_src
These changes might become obsolete with the [[https://www.reddit.com/r/emacs/comments/1j05761/anyone_tried_the_new_igcmps_garbage_collector/][IGC/MPS enhancements currently in development]].
** Package system and management
*** TODO Manage explicit list of packages (see [[https://www.reddit.com/r/emacs/comments/np6ey4/how_packageel_works_with_use_package/][this reddit post]])
** Default/Initial Frame
By default, we prefer frames to be rather minimal and distraction-less.
Concretely, we try to achieve this by removing most bars/widgets in the
default/base frame setup ([[https://www.gnu.org/software/emacs/manual/html_node/elisp/Initial-Parameters.html#index-default_002dframe_002dalist][default-frame-alist]]), effectively forcing operation to
be keyboard-driven.

For the specific settings, see the official [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Frame-Parameters.html][documentation on frame parameters]],
especially the part concerning [[www.gnu.org/software/emacs/manual/html_node/elisp/Window-Frame-Parameters.html][window frame parameters]].
#+begin_src emacs-lisp
;; Frame parameters
(setopt default-frame-alist
        '((fullscreen . maximize)
          (fullscreen-restore . fullheight)
          (border-width . 0)
          (internal-border-width . 0)
          (vertical-scroll-bars . nil)
          (horizontal-scroll-bars . nil)
          (menu-bar-lines . 0)
          (tool-bar-lines . 0)
          (tab-bar-lines . 0)
          (minibuffer. t)
          (top-visible . 5)
          (bottom-visible . 5)
          (visibility . t)
          (auto-raise . t)
          (auto-lower . nil)
          (left-fringe . 8)
          (right-fringe . 8)
          (left-divider-width . 3)
          (right-divider-width . 3)
          (cursor-type . (hbar . 3))))
#+end_src
* Initialization (init.el)
:PROPERTIES:
:ID:       43b929ca-f602-4d36-9b4e-ed056e2fdb58
:END:
[[https://www.gnu.org/software/emacs/manual/html_node/elisp/Init-File.html][The initialization file]] contains all customization and configuration that does
not go in the [[id:4c1ec44b-b1e3-4119-a293-e92b94145111][early initialization file]]; in particular, it is executed after
initialization of the GUI and enabling/activation of packages.
** Header
To ensure the buffer/file is evaluated using [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Selecting-Lisp-Dialect.html][modern Lisp dialect with lexical binding
(instead of dynamic)]], we set [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Selecting-Lisp-Dialect.html#index-lexical_002dbinding][lexical-binding]] (to `t') as a [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Specifying-File-Variables.html][file-local variable
in the first line of the file header]].
#+begin_src emacs-lisp
  ;; -*- lexical-binding: t; -*-
  ;; init.el
#+end_src
** Bootstrap
We start by setting up fundamental parts of the relevant environment and the
package system, as well as configure Emacs's launching behavior.
*** Basic directories and files
#+begin_src emacs-lisp
  ;;; Environment
#+end_src
**** Configuration
#+begin_src emacs-lisp
  ;; Config
  (defconst EMACS_CONFIG_DIR (file-name-as-directory
                              (if (getenv "XDG_CONFIG_HOME")
                                  (file-name-concat (getenv "XDG_CONFIG_HOME") "emacs/")
                                user-emacs-directory))
    "Directory where Emacs configuration is stored.")

  (defconst THEMES_DIR (file-name-as-directory (file-name-concat EMACS_CONFIG_DIR "themes/"))
    "Directory where (custom) themes are stored.")

  (defconst LOCAL_DIR (file-name-as-directory (file-name-concat EMACS_CONFIG_DIR "local/"))
    "Directory where (custom) local functionalities/packages are defined.")

  (defconst TEMPLATES_DIR (file-name-as-directory (file-name-concat EMACS_CONFIG_DIR "templates/"))
    "Directory where (custom) templates are defined.")

  (defconst MISC_DIR (file-name-as-directory (file-name-concat EMACS_CONFIG_DIR "misc/"))
    "Directory where (custom) miscellaneous configuration/settings are stored.")

  (defconst CUSTOM_FILE (file-name-concat MISC_DIR "custom-set.el")
    "File where (automatically generated) customization settings are stored.")
#+end_src
**** Data
**** Cache
*** Package system and management
*** Local Modules
*** Launching
** General Look and Feel
*** Frames, Windows, and Minibuffer
*** Movement and Navigation
*** Editing
** Directory and File Management (dired)
** Completion
*** Styles (orderless)
*** Functions (cape)
*** Minibuffer (vertico)
*** In-Buffer (corfu)
*** Templates (tempel)
** Advanced Actions
*** General (consult, embark)
*** Spooky Action at a Distance (avy, ace-window)
** Documents
*** Markdown (markdown-mode)
*** LaTeX (auctex, cdlatex, math-delimiters)
*** View (pdf-tools)
** Development
*** Version Control (magit, diffhl)
*** Formal Methods (proof-general, easycrypt, easycrypt-ext)
*** OCaml (tuareg, merlin)
** Org and Friends
** Themes (doom-themes)
** Miscellaneous
