--extended
--scheme=default
--tail=1000000
--multi
--wrap
--scroll-off=3
--hscroll-off=10
--filepath-word
--height=~60%
--tiebreak=chunk,length,index
--layout=reverse
--border=rounded
--margin=0,2.5%
--padding=0
--info=inline-right
--ansi
--tabstop=4
--highlight-line
--preview-label="| Preview |"
--preview-label-pos=0:top
--preview-window="right,50%,border-double,nowrap,nofollow,nocycle,noinfo,nohidden"
--walker=file,hidden
--walker-root=./
--walker-skip=.git
--bind="ctrl-c:abort,ctrl-g:abort"
--bind="enter:accept,double-click:accept"
--bind="alt-enter:accept-non-empty"
--bind="ctrl-q:close,esc:close"
--bind="ctrl-p:toggle-preview"
--bind="tab:toggle"
--bind="ctrl-left:backward-word,ctrl-right:forward-word"
--bind="ctrl-a:beginning-of-line,ctrl-e:end-of-line"
--bind="ctrl-y:yank"
--bind="down:down,up:up"
--bind="pgdn:page-down,pgup:page-up"
--bind="preview-scroll-down:preview-down,preview-scroll-up:preview-up"
--bind="shift-down:preview-page-down,shift-up:preview-page-up"
--bind="alt-backspace:backward-kill-word,alt-d:kill-word"
--bind="ctrl-k:kill-line"
--bind="alt-j:jump,jump:accept"
