#!/usr/bin/env sh
set -eu

# Setup utilities
script_dir="$(dirname -- "$(realpath "$0")")"
. "$script_dir/utils"


if [ "$(id -u)" -eq 0 ]; then
    setup_log_die "Run this script as the target regular user, not as root."
fi

if ! command -v zypper >/dev/null 2>&1; then
    setup_log_die "zypper is not available; this script is intended for openSUSE."
fi

setup_log_info "This script needs sudo for system configuration."
sudo -v || setup_log_die "Failed to obtain valid sudo credentials."


for bcmd in git make curl unzip stow; do
    if ! command -v "$bcmd" >/dev/null 2>&1; then
        setup_log_info "$bcmd is not installed. Installing..."
        sudo zypper --non-interactive --no-color install "$bcmd"
        setup_log_info "Installed $bcmd."
    fi
done

XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"
XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
XDG_BIN_HOME="${XDG_BIN_HOME:-$HOME/.local/bin}"
DOTS_DIR="${DOTS_DIR:-$XDG_DATA_HOME/dots}"
SRCS_DIR="${SRCS_DIR:-$XDG_DATA_HOME/srcs}"

if [ ! -d "$DOTS_DIR" ]; then
    setup_log_die "dotfiles directory not found: $DOTS_DIR"
fi


setup_log_info "Installing TeXLive..."
sudo zypper --non-interactive --no-color install texlive-scheme-full
setup_log_info "Installed TeXLive."


setup_log_info "Sourcing existing Rust environment if present..."

export CARGO_HOME="${CARGO_HOME:-$HOME/.cargo}"
export RUSTUP_HOME="${RUSTUP_HOME:-$HOME/.rustup}"

if [ -f "$CARGO_HOME/env" ]; then
    . "$CARGO_HOME/env"
    setup_log_info "Sourced existing Rust environment."
fi

setup_log_info "Installing (or updating) stable Rust toolchain..."

if ! command -v rustup >/dev/null 2>&1; then
    setup_log_info "rustup is not installed. Installing..."
    sudo zypper --non-interactive --no-color install rustup
    setup_log_info "Installed rustup."
fi

rustup toolchain install stable
rustup default stable
setup_log_info "Installed (or updated) stable Rust toolchain."

setup_log_info "Installing additional Rust components..."
rustup component add rustfmt clippy rust-analyzer rust-src
setup_log_info "Installed additional Rust components."


setup_log_info "Installing Golang and corresponding tools..."
sudo zypper --non-interactive --no-color install go gopls
setup_log_info "Installed Golang and corresponding tools."


setup_log_info "Installing C/C++ and corresponding tools..."
sudo zypper --non-interactive --no-color install -t pattern devel_C_C++
sudo zypper --non-interactive --no-color install clang clang-tools
setup_log_info "Installed C/C++ and corresponding tools."


setup_log_info "Installing Python3 and corresponding tools..."
sudo zypper --non-interactive --no-color install -t pattern devel_python3
pyflavor="$(python3 -c 'import sys; print(f"python{sys.version_info.major}{sys.version_info.minor}")')"
sudo zypper --non-interactive --no-color install "${pyflavor}-python-lsp-server-all"
setup_log_info "Installed Python3 and corresponding tools."


setup_log_info "Installing opam..."
sudo zypper --non-interactive --no-color install opam
setup_log_info "Installed opam."

if ! opam var root >/dev/null 2>&1; then
    setup_log_info "Initializing opam..."
    opam init -y --bare --disable-shell-hook

    cat >> "$HOME/.bashrc" <<'EOF'

# >>> Opam initialization >>>
OPAMROOT=${OPAMROOT:-$HOME/.opam}
[[ -r "$OPAMROOT/opam-init/init.sh" ]] && . "$OPAMROOT/opam-init/init.sh" >/dev/null 2>&1 || true
# <<< Opam initialization <<<
EOF

    setup_log_info "Initialized opam."
else
    setup_log_info "opam is already initialized."
fi

if ! opam switch list --short | grep -qx 'dev'; then
    setup_log_info "Creating opam switch 'dev'..."
    opam switch -y create dev ocaml-base-compiler
    setup_log_info "Created opam switch 'dev'."
fi

setup_log_info "Activating opam switch 'dev'..."
opam switch set dev
eval "$(opam env --switch=dev --set-switch)"
setup_log_info "Activated opam switch 'dev'."

setup_log_info "Installing OCaml and corresponding tools (in opam switch 'dev')..."
opam install -y dune ocaml-lsp-server odoc ocamlformat utop
setup_log_info "Installed OCaml and corresponding tools (in opam switch 'dev')."


setup_log_info "Installing EasyCrypt..."

setup_log_info "Installing EasyCrypt base dependencies (in opam switch 'dev')..."
opam pin -yn add easycrypt https://github.com/EasyCrypt/easycrypt.git
opam install -y --deps-only easycrypt
setup_log_info "Installed EasyCrypt base dependencies (in opam switch 'dev')."

setup_log_info "Building EasyCrypt..."
mkdir -p -- "$SRCS_DIR" "$XDG_BIN_HOME"
clone_or_update 'https://github.com/EasyCrypt/easycrypt.git' "$SRCS_DIR/easycrypt/"
make -C "$SRCS_DIR/easycrypt"
ln -srf -- "$SRCS_DIR/easycrypt/ec.native" "$XDG_BIN_HOME/easycrypt"
setup_log_info "Built EasyCrypt."

setup_log_info "Installing SMT provers (for EasyCrypt)..."

setup_log_info "Installing SMT prover '${cvcvers}'..."
cvcvers=cvc5-1.2.1
if [ -x "$SRCS_DIR/${cvcvers}/bin/cvc5" ]; then
    setup_log_info "Found SMT prover '${cvcvers}' locally."
else
    cvcdir=cvc5-Linux-x86_64-static-gpl
    cvczip=${cvcdir}.zip
    curl -fsSL -o "$HOME/${cvczip}" "https://github.com/cvc5/cvc5/releases/download/${cvcvers}/${cvczip}"
    unzip -d "$SRCS_DIR/${cvcvers}" "$HOME/${cvczip}"
    cp -a -- "$SRCS_DIR/${cvcvers}/${cvcdir}/." "$SRCS_DIR/${cvcvers}/"
    rm -rf -- "$SRCS_DIR/${cvcvers:?}/${cvcdir:?}/"
    rm -- "$HOME/${cvczip:?}"
fi

ln -srf -- "$SRCS_DIR/${cvcvers}/bin/cvc5" "$XDG_BIN_HOME/cvc5"
ln -srf -- "$SRCS_DIR/${cvcvers}/bin/cvc5" "$XDG_BIN_HOME/${cvcvers}"
setup_log_info "Installed SMT prover '${cvcvers}'."

setup_log_info "Installing SMT prover '${z3vers}'..."
z3vers=z3-4.13.4
if [ -x "$SRCS_DIR/${z3vers}/bin/z3" ]; then
    setup_log_info "Found SMT prover '${z3vers}' locally."
else
    z3dir=z3-4.13.4-x64-glibc-2.35
    z3zip=${z3dir}.zip
    curl -fsSL -o "$HOME/${z3zip}" "https://github.com/Z3Prover/z3/releases/download/${z3vers}/${z3zip}"
    unzip -d "$SRCS_DIR/${z3vers}" "$HOME/${z3zip}"
    cp -a -- "$SRCS_DIR/${z3vers}/${z3dir}/." "$SRCS_DIR/${z3vers}"
    rm -rf -- "$SRCS_DIR/${z3vers:?}/${z3dir:?}"
    rm -- "$HOME/${z3zip:?}"
fi

ln -srf -- "$SRCS_DIR/${z3vers}/bin/z3" "$XDG_BIN_HOME/z3"
ln -srf -- "$SRCS_DIR/${z3vers}/bin/z3" "$XDG_BIN_HOME/${z3vers}"
setup_log_info "Installed SMT prover '${z3vers}'."

setup_log_info "Installed SMT provers (for EasyCrypt)."

setup_log_info "Configuring EasyCrypt..."
easycrypt why3config
(cd -- "$DOTS_DIR" && stow easycrypt)
setup_log_info "Configured EasyCrypt."

setup_log_info "Installed EasyCrypt."


setup_log_info "Installing Lean..."
curl -fsSL https://elan.lean-lang.org/elan-init.sh | sh -s -- -y --no-modify-path
setup_log_info "Installed Lean."


setup_log_info "Installing (and enabling) Docker..."
sudo zypper --non-interactive --no-color install docker
sudo systemctl enable --now docker
sudo usermod -aG docker "$USER"
setup_log_info "Installed (and enabled) Docker."


setup_log_action "Manual checkpoint:"
setup_log_action "  Reboot."
