#!/usr/bin/env sh
set -eu

# Setup utilities
script_dir="$(dirname -- "$(realpath "$0")")"
. "$script_dir/utils"


if [ "$(id -u)" -eq 0 ]; then
    setup_log_die "Run this script as the target regular user, not as root."
fi

if ! command -v zypper >/dev/null 2>&1; then
    setup_log_die "zypper is not available; this script is intended for openSUSE."
fi

for pcmd in age proton-drive protonmail-bridge; do
    if ! command -v proton-drive >/dev/null 2>&1; then
        setup_log_die "$pcmd is not available; please follow installation instructions in order."
    fi
done

setup_log_info "This script needs sudo for system configuration."
sudo -v || setup_log_die "Failed to obtain valid sudo credentials."


for bcmd in git stow; do
    if ! command -v "$bcmd" >/dev/null 2>&1; then
        setup_log_info "$bcmd is not installed. Installing..."
        sudo zypper --non-interactive --no-color install "$bcmd"
        setup_log_info "Installed $bcmd."
    fi
done

XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"
XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
XDG_BIN_HOME="${XDG_BIN_HOME:-$HOME/.local/bin}"
DOTS_DIR="${DOTS_DIR:-$XDG_DATA_HOME/dots}"

MAILDIR="${MAILDIR:-$XDG_DATA_HOME/mail}"
# AUTHINFO_FILE="${AUTHINFO_FILE:-$XDG_DATA_HOME/.authinfo.gpg}"

MANPATH="${MANPATH:-}"
INFOPATH="${INFOPATH:-}"

if [ -n "${XDG_RUNTIME_DIR:-}" ]; then
    SSH_AUTH_SOCK="${SSH_AUTH_SOCK:-$XDG_RUNTIME_DIR/ssh-agent.socket}"
else
    SSH_AUTH_SOCK="${SSH_AUTH_SOCK:-}"
fi

if [ ! -d "$DOTS_DIR" ]; then
    setup_log_die "dotfiles directory not found: $DOTS_DIR"
fi

REPLACE_PLACEHOLDER="${REPLACE_PLACEHOLDER:-$DOTS_DIR/setup/scripts/replace-placeholder}"

if [ ! -x "$REPLACE_PLACEHOLDER" ]; then
    setup_log_die "replace-placeholder script not found or not executable: $REPLACE_PLACEHOLDER"
fi


AUTHINFO_FILE="${AUTHINFO_FILE:-$XDG_DATA_HOME/.authinfo.age}"
authinfo_dir="$(dirname -- "$AUTHINFO_FILE")"
install -d -m 700 "$authinfo_dir"

if ! pass-cli test >/dev/null 2>&1; then
    setup_log_die "Cannot authenticate to password manager, please ensure you are logged in (pass-cli login)."
fi

if [ -e "$AUTHINFO_FILE" ]; then
    setup_log_info "Authinfo file already exists; skipping creation: $AUTHINFO_FILE."
else
    (
        set +x
        umask 077
        authinfo_tmpdir="$(mktemp -d "${XDG_RUNTIME_DIR:-/tmp}/authinfo.XXXXXX")"
        chmod 700 "$authinfo_tmpdir"

        authinfo_tmp="$authinfo_tmpdir/authinfo"
        authinfo_age_tmp="$authinfo_dir/.authinfo.age.XXXXXX"

        trap 'rm -rf -- "$authinfo_tmpdir"; rm -f -- "$authinfo_age_tmp"' EXIT HUP INT TERM

        setup_log_info "Fetching credentials from password manager..."

        github_pers_user="$(pass-cli item view --vault-name Personal --item-name github-personal --field username)"
        github_pers_pat="$(pass-cli item view --vault-name Personal --item-name github-personal --field personal-access-token)"
        github_prof_user="$(pass-cli item view --vault-name Personal --item-name github-professional --field username)"
        github_prof_pat="$(pass-cli item view --vault-name Personal --item-name github-professional --field personal-access-token)"

        cat > "$authinfo_tmp" <<EOF
machine api.github.com login ${github_pers_user}^forge password $github_pers_pat
machine api.github.com login ${github_prof_user}^forge password $github_prof_pat
EOF

        age --encrypt \
            --recipient "$XDG_CONFIG_HOME/age/recipients/mm_personal_file_enc_primary.recipient"\
            --recipient "$XDG_CONFIG_HOME/age/recipients/mm_personal_file_enc_secondary.recipient"\
            --recipient "$XDG_CONFIG_HOME/age/recipients/mm_personal_file_enc_tertiary.recipient"\
            --output "$authinfo_age_tmp" \
            "$authinfo_tmp"

        chmod 600 "$authinfo_age_tmp"
        mv -- "$authinfo_age_tmp" "$AUTHINFO_FILE"
    )

    setup_log_info "Created Authinfo file."
fi


setup_log_info "Creating mail directories..."

# install -d -m 700 -- \
#         "$MAILDIR" \
#         "$MAILDIR/personal-mmeijers" \
#         "$MAILDIR/kernel-mmeijers" \
#         "$MAILDIR/kem-mmeijers" \
#         "$MAILDIR/research-mmeijers" \
#         "$MAILDIR/teaching-mmeijers" \
#         "$MAILDIR/host-mmeijers" \
#         "$MAILDIR/contracting-mmeijers" \
#         "$MAILDIR/dump-mmeijers"
install -d -m 700 -- \
        "$MAILDIR" \
        "$MAILDIR/matthiasmeijers-proton" \
        "$MAILDIR/personal-mmeijers" \
        "$MAILDIR/kernel-mmeijers" \
        "$MAILDIR/kem-mmeijers"

setup_log_info "Created mail directories."

setup_log_info "Synchronizing mail directories..."

sudo zypper --non-interactive --no-color install isync maildir-utils
(cd -- "$DOTS_DIR" && stow isync)

"$REPLACE_PLACEHOLDER" XDG_CONFIG_HOME "$XDG_CONFIG_HOME" \
    "$XDG_CONFIG_HOME/isyncrc-temp" \
    "$XDG_CONFIG_HOME/isyncrc"

"$REPLACE_PLACEHOLDER" XDG_DATA_HOME "$XDG_DATA_HOME" \
    "$XDG_CONFIG_HOME/isyncrc"

if ! command -v mbsync >/dev/null 2>&1; then
    setup_log_die "mbsync is not available after installing isync."
fi

mbsync --all --verbose

setup_log_info "Synchronized mail directories."


setup_log_info "Installing spellchecker and dictionaries..."

sudo zypper --non-interactive --no-color install \
     hunspell \
     'myspell-en*' \
     'myspell-nl*' \
     'myspell-de*' \
     'myspell-fr*' \
     'myspell-es*'

setup_log_info "Installed spellchecker and dictionaries."


setup_log_info "Installing editor (Emacs)..."

sudo zypper --non-interactive --no-color install emacs emacs-x11 mu4e pinentry-emacs
ln -sf -- "$(which emacs-x11)" "$XDG_BIN_HOME/emacs"

(cd -- "$DOTS_DIR" && stow emacs)

mkdir -p -- "$XDG_CONFIG_HOME/systemd/user"

cat > "$XDG_CONFIG_HOME/systemd/user/emacs.service" <<EOF
[Unit]
Description=Emacs text editor
Documentation=info:emacs man:emacs(1) https://gnu.org/software/emacs/

[Service]
Type=notify
ExecStart=$XDG_BIN_HOME/emacs --fg-daemon

# Emacs will exit with status 15 after having received SIGTERM, which
# is the default "KillSignal" value systemd uses to stop services.
SuccessExitStatus=15
Restart=on-failure

# Environment
Environment="XDG_CONFIG_HOME=$XDG_CONFIG_HOME"
Environment="XDG_DATA_HOME=$XDG_DATA_HOME"
Environment="XDG_CACHE_HOME=$XDG_CACHE_HOME"
Environment="XDG_STATE_HOME=$XDG_STATE_HOME"
Environment="XDG_BIN_HOME=$XDG_BIN_HOME"
Environment="PATH=$PATH"
Environment="MANPATH=$MANPATH"
Environment="INFOPATH=$INFOPATH"
Environment="MAILDIR=$MAILDIR"
Environment="AUTHINFO_FILE=$AUTHINFO_FILE"
Environment="SSH_AUTH_SOCK=$SSH_AUTH_SOCK"

[Install]
WantedBy=default.target
EOF

systemctl --user daemon-reload
systemctl --user enable emacs.service

# setup_log_info "Installing/initializing Emacs packages..."

# clone_or_update 'git@github-personal:mmctl/org.git' "$XDG_DATA_HOME/org"

# emacs --batch \
#       --load "$XDG_CONFIG_HOME/emacs/early-init.el" \
#       --load "$XDG_CONFIG_HOME/emacs/init.el" \
#       --load "$XDG_DATA_HOME/emacs/install/install-treesit.el"
#       --load "$XDG_DATA_HOME/emacs/install/wait-native-comp.el"

# setup_log_info "Installed Emacs packages."

setup_log_info "Fetching Emacs ORG data..."
clone_or_update 'git@github-personal:mmctl/org.git' "$XDG_DATA_HOME/org"
setup_log_info "Fetched Emacs ORG data."


setup_log_info "Initializing mu/mu4e (mail)..."

mu init --maildir="$MAILDIR"
mu index

setup_log_info "Initialized mu/mu4e."


setup_log_info "Setting default file associations..."

if command -v xdg-mime >/dev/null 2>&1; then

    mkdir -p "$XDG_DATA_HOME/applications"

        cat > "$XDG_DATA_HOME/applications/emacsclient.desktop" <<'EOF'
[Desktop Entry]
Name=Emacsclient
Comment=Run Emacsclient, starting a server if none is currently running
Exec=emacsclient --alternate-editor= --create-frame %F
Icon=emacs
Categories=Development;TextEditor;Utility;
MimeType=text/plain;text/english;text/x-c;text/x-csrc;text/x-chdr;text/x-c++src;text/x-c++hdr;text/x-python;text/x-shellscript;text/x-tex;text/markdown;application/x-shellscript;application/json;application/xml;
NoDisplay=true
Terminal=false
Type=Application
EOF

    cat > "$XDG_DATA_HOME/applications/emacsclient-mail.desktop" <<'EOF'
[Desktop Entry]
Name=Emacsclient Mail
Comment=Compose mail with Emacsclient
Categories=Network;Email;
Exec=emacsclient --alternate-editor= --create-frame --eval '(message-mailto "%u")'
Icon=emacs
MimeType=x-scheme-handler/mailto;
NoDisplay=true
Terminal=false
Type=Application
EOF

    update-desktop-database "$XDG_DATA_HOME/applications"

    xdg-mime default emacsclient.desktop text/plain
    xdg-mime default emacsclient-mail.desktop x-scheme-handler/mailto

    setup_log_info "Set default file associations."
else
    setup_log_warn "xdg-mime not installed; skipping file associations."
fi

setup_log_info "Installed editor (Emacs)."


setup_log_info "Cleaning up..."
rm -f -- "$HOME/.emacs"
rm -rf -- "$HOME/.emacs.d"
setup_log_info "Cleaned up."


setup_log_action "Manual checkpoint:"
setup_log_action "  Run non-daemon Emacs (emacs), load the install script, and wait for native compilation to finish:"
setup_log_action "    (load \"$XDG_DATA_HOME/emacs/install/install-entry.el\")"
setup_log_action "  Reboot."
