#!/usr/bin/env sh
set -eu

# Setup utilities
script_dir="$(dirname -- "$(realpath "$0")")"
. "$script_dir/utils"


if [ "$(id -u)" -eq 0 ]; then
    setup_log_die "Run this script as the target regular user, not as root."
fi

if ! command -v zypper >/dev/null 2>&1; then
    setup_log_die "zypper is not available; this script is intended for openSUSE."
fi

setup_log_info "This script needs sudo for system configuration."
sudo -v || setup_log_die "Failed to obtain valid sudo credentials."


XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}


setup_log_info "Installing graphical file manager (Nautilus)..."
sudo zypper --non-interactive --no-color install nautilus
setup_log_info "Installed graphical file manager (Nautilus)."


setup_log_info "Installing browser (Firefox)..."

(cd -- "$DOTS_DIR" && stow firefox)

sudo zypper --non-interactive --no-color install MozillaFirefox
firefox -CreateProfile "default $XDG_CONFIG_HOME/mozilla/firefox/default"

xdg-mime default firefox.desktop \
  x-scheme-handler/http x-scheme-handler/https x-scheme-handler/chrome \
  text/html text/xml \
  application/xml application/xhtml+xml

setup_log_info "Installed browser (Firefox)."


setup_log_info "Installing Flatpak with Flathub..."

sudo zypper --non-interactive --no-color install flatpak
flatpak --user remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

setup_log_info "Installed Flatpak with Flathub."


setup_log_info "Installing messenger (Signal)..."
flatpak --user install flathub -y org.signal.Signal
setup_log_info "Installed messenger (Signal)."

setup_log_info "Installing research tools (Zotero)..."

flatpak --user install flathub -y org.zotero.Zotero
flatpak --user override \
  --nofilesystem=home \
  --persist=.zotero \
  --persist=Zotero \
  org.zotero.Zotero

setup_log_info "Installed research tools (Zotero)."


setup_log_action "Manual checkpoint:"
setup_log_action "  Relog."
setup_log_action "  Link to Signal."
setup_log_action "  Log in to Zotero."
setup_log_action "  Open Firefox browser and setup to preference:"
setup_log_action "    Log in to Proton and check \"Keep me signed in\" on a trusted device:"
setup_log_action "      https://account.proton.me/login"
setup_log_action "    Install the following extensions:"
setup_log_action "      Proton Pass, "
setup_log_action "      uBlock Origin (enable filter lists), and"
setup_log_action "      Zotero Connector."
setup_log_action "    Register exceptions, e.g., for storage of browsing data/cookies."
