#!/usr/bin/env sh
set -eu

# Setup utilities
script_dir="$(dirname -- "$(realpath "$0")")"
. "$script_dir/utils"


if [ "$(id -u)" -eq 0 ]; then
    setup_log_die "Run this script as the target regular user, not as root."
fi

if ! command -v zypper >/dev/null 2>&1; then
    setup_log_die "zypper is not available; this script is intended for openSUSE."
fi

setup_log_info "This script needs sudo for system configuration."
sudo -v || setup_log_die "Failed to obtain valid sudo credentials."


for bcmd in git curl; do
    ensure_command_from_package "$bcmd" "$bcmd"
done


XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
SRCS_DIR="${SRCS_DIR:-$XDG_DATA_HOME/srcs}"


setup_log_info "Creating PARA directories..."

PARA_ROOT_DIR="${PARA_ROOT_DIR:-$HOME/para}"
PROJECTS_DIR="${PROJECTS_DIR:-$PARA_ROOT_DIR/projects}"
AREAS_DIR="${AREAS_DIR:-$PARA_ROOT_DIR/areas}"
RESOURCES_DIR="${RESOURCES_DIR:-$PARA_ROOT_DIR/resources}"
ARCHIVES_DIR="${ARCHIVES_DIR:-$PARA_ROOT_DIR/archives}"

install -d -m 700 -- \
        "$PARA_ROOT_DIR" \
        "$PROJECTS_DIR" \
        "$AREAS_DIR" \
        "$RESOURCES_DIR" \
        "$ARCHIVES_DIR"

setup_log_info "Created PARA directories."



setup_log_info "Setting up areas..."


setup_log_info "Setting up area 'keyboards'..."

keyboards_area_dir="$AREAS_DIR/keyboards"
keyboards_source_dir="$keyboards_area_dir/workspace/source"
qmk_home_dir="$keyboards_source_dir/qmk_firmware"

install -d -m 700 -- "$keyboards_source_dir"

setup_log_info "Installing qmk..."

curl -fsSL https://install.qmk.fm | sh -s -- --confirm
qmk setup -y --home="$qmk_home_dir"

setup_log_info "Installed qmk."

clone_or_update 'git@github-personal:mmctl/keyboards.git' "$keyboards_source_dir/keyboards"
ln -srf -- "$keyboards_source_dir/keyboards/qmk-boards/lily58/rev1/mb/mmbasic" "$qmk_home_dir/keyboards/lily58/keymaps/mmbasic"
ln -srf -- "$keyboards_source_dir/keyboards/qmk-boards/lily58/rev1/mb/mmhrm" "$qmk_home_dir/keyboards/lily58/keymaps/mmhrm"

setup_log_info "Set up area 'keyboards'."


setup_log_info "Setting up area 'website'..."

setup_log_info "Installing hugo..."
sudo zypper --non-interactive --no-color install hugo
setup_log_info "Installed hugo."

install -d -m 700 -- "$AREAS_DIR/website/workspace"
clone_or_update --recurse-submodules 'git@github-personal:mmctl/website-personal.git' "$AREAS_DIR/website/workspace/source"

setup_log_info "Set up area 'website'."

setup_log_info "Setting up area 'development'..."

development_area_dir="$AREAS_DIR/development"
install -d -m 700 -- "$development_area_dir"

setup_log_info "Setting up development subarea 'easycrypt'..."
install -d -m 700 -- "$development_area_dir/easycrypt/workspace"
clone_or_update 'git@github-research:EasyCrypt/easycrypt.git' "$development_area_dir/easycrypt/workspace/source"
setup_log_info "Set up development subarea 'easycrypt'."

setup_log_info "Setting up development subarea 'emacs'..."
install -d -m 700 -- "$development_area_dir/emacs/workspace/source"
clone_or_update 'git@github-personal:mmctl/easycrypt-ext.git' "$development_area_dir/emacs/workspace/source/easycrypt-ext"
clone_or_update 'git@github-personal:mmctl/move-it.git' "$development_area_dir/emacs/workspace/source/move-it"
setup_log_info "Set up development subarea 'emacs'."

setup_log_info "Set up area 'development'."

setup_log_info "Setting up area 'work'..."
install -d -m 700 -- "$AREAS_DIR/work/workspace/source"
clone_or_update 'git@github-personal:mmctl/cvcl.git' "$AREAS_DIR/work/workspace/source/cvcl"
setup_log_info "Set up area 'work'."


setup_log_info "Setting up projects..."

setup_log_info "Setting up project 'latex-dissertation-template'..."
install -d -m 700 -- "$PROJECTS_DIR/dissertation-template" "$PROJECTS_DIR/dissertation-template/workspace"
clone_or_update 'git@github-personal:mmctl/latex-dissertation-template.git' "$PROJECTS_DIR/dissertation-template/workspace/source"
setup_log_info "Set up project 'latex-dissertation-template'."

setup_log_info "Set up projects."


setup_log_info "Creating user-wide PARA environment (systemd)..."

mkdir -p -- "$HOME/.config/environment.d"

cat > "$HOME/.config/environment.d/50-para-dirs.conf" <<EOF
PARA_ROOT_DIR="$PARA_ROOT_DIR"
PROJECTS_DIR="$PROJECTS_DIR"
AREAS_DIR="$AREAS_DIR"
RESOURCES_DIR="$RESOURCES_DIR"
ARCHIVES_DIR="$ARCHIVES_DIR"
EOF

setup_log_info "Created user-wide PARA environment (systemd)."
