#!/usr/bin/env sh
set -eu

# Setup utilities
script_dir="$(dirname -- "$(realpath "$0")")"
. "$script_dir/utils"


if [ "$(id -u)" -eq 0 ]; then
    setup_log_die "Run this script as the target regular user, not as root."
fi

if ! command -v zypper >/dev/null 2>&1; then
    setup_log_die "zypper is not available; this script is intended for openSUSE."
fi

setup_log_info "This script needs sudo for system configuration."
sudo -v || setup_log_die "Failed to obtain valid sudo credentials."


for bcmd in git curl; do
    if ! command -v "$bcmd" >/dev/null 2>&1; then
        setup_log_info "$bcmd is not installed. Installing..."
        sudo zypper --non-interactive --no-color install "$bcmd"
        setup_log_info "Installed $bcmd."
    fi
done

XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"


setup_log_info "Creating PARA directories..."

PROJECTS_DIR="${PROJECTS_DIR:-$HOME/projects}"
AREAS_DIR="${AREAS_DIR:-$HOME/areas}"
RESOURCES_DIR="${RESOURCES_DIR:-$HOME/resources}"
ARCHIVES_DIR="${ARCHIVES_DIR:-$HOME/archives}"

install -d -m 700 -- \
        "$PROJECTS_DIR" \
        "$AREAS_DIR" \
        "$RESOURCES_DIR" \
        "$ARCHIVES_DIR"

setup_log_info "Created PARA directories."


setup_log_info "Setting up projects..."

setup_log_info "Setting up project 'keyboard'..."

setup_log_info "Installing qmk..."
curl -fsSL https://install.qmk.fm | sh -s -- --confirm
qmk setup -y --home="$XDG_DATA_HOME/qmk_firmware"
setup_log_info "Installed qmk."

clone_or_update 'git@github-personal:mmctl/keyboards.git' "$PROJECTS_DIR/keyboards"
ln -srf -- "$PROJECTS_DIR/keyboards/lily58/rev1/mb/mmbasic" "$XDG_DATA_HOME/qmk_firmware/keyboards/lily58/keymaps/mmbasic"
ln -srf -- "$PROJECTS_DIR/keyboards/lily58/rev1/mb/mmhrm" "$XDG_DATA_HOME/qmk_firmware/keyboards/lily58/keymaps/mmhrm"

setup_log_info "Set up project 'keyboard'."

setup_log_info "Setting up project 'website'..."

setup_log_info "Installing hugo..."
sudo zypper --non-interactive --no-color install hugo
setup_log_info "Installed hugo."

clone_or_update --recurse-submodules \
                'git@github-personal:mmctl/website-personal.git' \
                "$PROJECTS_DIR/website"

setup_log_info "Set up project 'website'."

setup_log_info "Setting up project 'easycrypt-dev'..."
clone_or_update 'git@github-work:EasyCrypt/easycrypt.git' "$PROJECTS_DIR/easycrypt-dev"
setup_log_info "Set up project 'easycrypt-dev'."

setup_log_info "Setting up project 'emacs-dev'..."
install -d -m 700 -- "$PROJECTS_DIR/emacs-dev"
clone_or_update 'git@github-personal:mmctl/easycrypt-ext.git' "$PROJECTS_DIR/emacs-dev/easycrypt-ext"
clone_or_update 'git@github-personal:mmctl/move-it.git' "$PROJECTS_DIR/emacs-dev/move-it"
setup_log_info "Set up project 'emacs-dev'."

setup_log_info "Setting up project 'latex-dissertation-template'..."
clone_or_update 'git@github-personal:mmctl/latex-dissertation-template.git' "$PROJECTS_DIR/latex-dissertation-template"
setup_log_info "Set up project 'latex-dissertation-template'."


setup_log_info "Setting up areas..."

setup_log_info "Setting up area 'work'..."
install -d -m 700 -- "$AREAS_DIR/work"
clone_or_update 'git@github-personal:mmctl/cvcl.git' "$AREAS_DIR/work/cvcl"
setup_log_info "Set up area 'work'."
