icons_format = "{icon}"

[theme]
theme = "nord"


[icons]
icons = "material-nf"


[[block]]
block = "net"
format = " $icon $device{: $ip|} "
format_alt = " $icon $device: ^icon_net_down $speed_down.eng(w:2,prefix:Ki) ^icon_net_up $speed_up.eng(w:2,prefix:Ki) "
inactive_format = " $icon $device: Inactive "
missing_format = " $icon No Interface "
interval = 3

[[block.click]]
button = "left"
action = "toggle_format"


[[block]]
block = "disk_space"
format = " $icon $percentage.eng(w:2) "
format_alt = " $icon $used.eng(w:2,prefix:Gi)/$total.eng(w:2,prefix:Gi)"
path = "/"
info_type = "used"
interval = 30
warning = 75
alert = 90

[block.icons_overrides]
disk_drive = "\uf0a0"

[[block.click]]
button = "left"
action = "toggle_format"

[[block.click]]
button = "right"
action = "update"


[[block]]
block = "memory"
format = " $icon_swap $swap_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used.eng(w:2,prefix:Mi)/$swap_total.eng(w:2,prefix:Mi) "
interval = 5
warning_swap = 80
critical_swap = 95

[block.icons_overrides]
memory_swap = "\uebcb"

[[block.click]]
button = "left"
action = "toggle_format"

[[block.click]]
button = "right"
cmd = "alacritty --command htop --sort-key M_SWAP"


[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:2) "
format_alt = " $icon $mem_used.eng(prefix:Mi)/$mem_total.eng(prefix:Mi) "
interval = 5
warning_mem = 80
critical_mem = 95

[block.icons_overrides]
memory_mem = "\uefc5"

[[block.click]]
button = "left"
action = "toggle_format"

[[block.click]]
button = "right"
cmd = "alacritty --command htop --sort-key PERCENT_MEM"


[[block]]
block = "cpu"
format = " $icon $utilization.eng(w:2) "
format_alt = " $icon $frequency.eng(w:2) "
interval = 5
info_cpu = 30
warning_cpu = 70
critical_cpu = 90

[[block.click]]
button = "left"
action = "toggle_format"

[[block.click]]
button = "right"
cmd = "alacritty --command htop --sort-key PERCENT_CPU"


[[block]]
block = "sound"
format = " $icon {$volume.eng(w:2) |}"
device_kind = "sink"
device = "default"
show_volume_when_muted = true
step_width = 2

[[block.click]]
button = "left"
action = "toggle_mute"

[[block.click]]
button = "right"
cmd = "pavucontrol"


[[block]]
block = "time"
interval = 1

[block.format]
full = " $timestamp.datetime(f:'%A %d/%m/%Y %H:%M:%S') "
short = " $timestamp.datetime(f:'%a %d/%m %H:%M') "
