format = """
[](os_bg)\
$os\
$username\
$hostname\
[](bg:dir_bg fg:os_bg)\
$directory\
[](bg:git_bg fg:dir_bg)\
$git_branch\
$git_status\
[](bg:lang_bg fg:git_bg)\
$c\
$python\
$rust\
$golang\
[](fg:lang_bg)\
$fill\
$status
$character
"""
scan_timeout = 50
command_timeout = 500
add_newline = true
palette = 'gen'

[os]
format = '[$symbol ]($style)'
style = 'bg:os_bg fg:on_os'
disabled = false

[username]
format = '[$user ]($style)'
style_root = 'bg:os_bg fg:error'
style_user = 'bg:os_bg fg:on_os'
show_always = true
disabled = false

[hostname]
format = '[$hostname $ssh_symbol ]($style)'
style = 'bg:os_bg fg:on_os'
ssh_symbol = ' '
ssh_only = true
trim_at = '.'
disabled = false

[directory]
format = '[ $path ]($style)[$read_only]($read_only_style)'
style = 'bg:dir_bg fg:on_dir'
read_only_style = 'bg:dir_bg fg:warning'
read_only = '󰌱 '
truncation_length = 2
truncation_symbol = '.../'
truncate_to_repo = true
use_os_path_sep = true
disabled = false

[git_branch]
format = '[ $symbol $branch ]($style)'
style = 'bg:git_bg fg:on_git'
symbol = ' '
truncation_length = 50
truncation_symbol = '...'

[git_status]
format = '[(| $ahead_behind )(| $conflicted )(| $staged$modified$deleted$renamed$typechanged )(| $stashed )]($style)'
style = 'bg:git_bg fg:on_git'
ahead = '⇡ ${count}'
diverged = '⇕ ⇡ ${ahead_count}⇣ ${behind_count}'
behind = '⇣ ${count}'
up_to_date = ' '
conflicted = '󱚞 '
staged = '󰴥 '
modified = ' '
deleted = ' '
renamed = ' '
typechanged = ' '
stashed = ''

[c]
symbol = ' '
style = 'bg:lang_bg fg:on_lang'
format = '[ $symbol ($version(-$name)) ]($style)'

[python]
symbol = ' '
style = 'bg:lang_bg fg:on_lang'
format = '[ $symbol ($version) (\($virtualenv\)) ]($style)'

[haskell]
symbol = ' '
style = 'bg:lang_bg fg:on_lang'
format = '[ $symbol ($version) ]($style)'

[java]
symbol = ' '
style = 'bg:lang_bg fg:on_lang'
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ''
style = 'bg:lang_bg fg:on_lang'
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = '󰟓'
style = 'bg:lang_bg fg:on_lang'
format = '[ $symbol ($version) ]($style)'

[status]
format = '[ $symbol$status( \(ERR: $common_meaning\))( \(SIG: $signal_name\)) ]($style)'
style = 'bg:status_bg fg:on_status'
success_symbol = ''
symbol = '[󰯆 ](fg:error bg:status_bg)'
not_executable_symbol = '[ ](fg:error bg:status_bg)'
not_found_symbol = '[ ](fg:error bg:status_bg)'
sigint_symbol = '[󱐋](fg:warning bg:status_bg)'
signal_symbol = '[󱐋](fg:error bg:status_bg)'
recognize_signal_code = true
map_symbol = true
disabled = false

[character]
format = ' $symbol  '
success_symbol = '[󱞩](fg:success)'
error_symbol = '[󱞩](fg:error)'
disabled = false

[fill]
symbol = ' '
disabled = false


[os.symbols]
Alpaquita = ' '
Alpine = ' '
Amazon = ' '
Android = ' '
Arch = ' '
Artix = ' '
CentOS = ' '
Debian = ' '
DragonFly = ' '
Emscripten = ' '
EndeavourOS = ' '
Fedora = ' '
FreeBSD = ' '
Garuda = '󰛓 '
Gentoo = ' '
HardenedBSD = '󰞌 '
Illumos = '󰈸 '
Linux = ' '
Mabox = ' '
Macos = ' '
Manjaro = ' '
Mariner = ' '
MidnightBSD = ' '
Mint = ' '
NetBSD = ' '
NixOS = ' '
OpenBSD = '󰈺 '
openSUSE = ' '
OracleLinux = '󰌷 '
Pop = ' '
Raspbian = ' '
Redhat = ' '
RedHatEnterprise = ' '
Redox = '󰀘 '
Solus = '󰠳 '
SUSE = ' '
Ubuntu = ' '
Unknown = ' '
Windows = '󰍲 '
