# Yazi configuration file (main)

## Manager
[mgr]
ratio = [1, 3, 4]
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
sort_translit = false
linemode = "size_and_mtime"
show_hidden = true
show_symlink = true
scrolloff = 5
mouse_events = ["click", "scroll", "move", "drag"]
title_format = "Yazi: {cwd}"


## Preview
[preview]
wrap = "yes"
tab_size = 4
max_width = 1440
max_height = 1080
cache_dir = "/home/mm/.cache/yazi"
#cache_dir = "$XDG_CACHE_HOME/yazi"
image_delay = 50
image_filter = "triangle"
image_quality = 75
sixel_fraction = 15
ueberzug_scale = 1
ueberzug_offset = [0, 0, 0, 0]


## Opener
[opener]
### Edit
edit = [
    { run = '$EDITOR "$@"', desc = "Default editor ($EDITOR)", block = true, for = "unix" },
]
### Open
open = [
    { run = 'xdg-open "$1"', desc = "Open", for = "linux" },
    { run = 'ya emit plugin open-with-cmd', desc = "Open with...", for = "linux" },
]
### Extract
extract = [
    { run = 'ya pub augmented-extract --list "$@"', desc = "Extract here", for = "unix" },
]
### Play
play = [
    { run = 'mpv --force-window "$@"', orphan = true, desc = "Play (MPV)", for = "unix" },
    { run = '''mediainfo "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show media info", for = "unix" },
]
### Visit
visit = [
    { run = 'ya emit cd "$(dirname "$1")"', desc = "Visit", for = "unix" },
    { run = 'ya emit tab_create "$(dirname "$1")"', desc = "Visit (in new tab)", for = "unix" },
]
### Meta (information)
meta = [
    { run = '''exiftool "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show EXIF", for = "unix" },
]


## Open
[open]
rules = [
    ### Folder
    { name = "*/", use = [ "edit", "open", "visit", "meta" ] },
    ### Text
    { mime = "text/*", use = [ "edit", "open", "visit", "meta" ] },
    ### Image
    { mime = "image/*", use = [ "open", "visit", "meta" ] },
    ### Media
    { mime = "{audio,video}/*", use = [ "play", "open", "visit", "meta" ] },
    ### Archive
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = [ "extract", "visit", "meta" ] },
    ### JS(ON)
    { mime = "application/{json,ndjson}", use = [ "edit", "open", "visit", "meta" ] },
    { mime = "*/javascript", use = [ "edit", "open", "visit", "meta" ] },
    ### Empty file
    { mime = "inode/empty", use = [ "edit", "open", "visit", "meta" ] },
    ### Fallback
    { name = "*", use = [ "open", "visit", "meta" ] },
]


## Tasks
[tasks]
micro_workers    = 10
macro_workers    = 10
bizarre_retry    = 2
suppress_preload = false
image_alloc      = 536870912  # 512MB
image_bound      = [ 0, 0 ]


## Plugin
[plugin]
append_previewers = [
    { name = "*", run = 'piper -- hexyl --terminal-width "$w" -g 2 "$1"'}
]


## Input
[input]
cursor_blink = true


## Confirm
[confirm]


## Pick
[pick]


## Which
[which]
sort_by = "key"
sort_sensitive = false
sort_reverse = false
sort_translit = false
