# Copy/Paste
map alt+x>w copy_to_clipboard
map alt+x>alt+w launch --stdin-source=@last_cmd_output --type=clipboard
map alt+x>y paste_from_clipboard

# Clear terminal
map ctrl+shift+l clear_terminal to_cursor_scroll active
map alt+x>l clear_terminal clear active

# Reset terminal
map alt+x>r clear_terminal reset active

# Fonts
map ctrl+shift+minus change_font_size current -2.0
map ctrl+shift+plus change_font_size current +2.0
map ctrl+shift+equal change_font_size current +2.0
map ctrl+shift+0 change_font_size current 0

map ctrl+alt+minus change_font_size all -2.0
map ctrl+alt+plus change_font_size all +2.0
map ctrl+alt+equal change_font_size all +2.0
map ctrl+alt+0 change_font_size all 0

# Scrolling
map ctrl+shift+p scroll_to_prompt -1
map ctrl+shift+n scroll_to_prompt 1
map ctrl+shift+o scroll_to_prompt 0

# Detaching
map alt+x>d detach_tab
map alt+x>ctrl+d detach_window

# Opening/Closing
map ctrl+shift+t new_tab
map ctrl+alt+t new_tab_with_cwd
map ctrl+shift+q close_tab
map ctrl+shift+w new_window
map ctrl+alt+w new_window_with_cwd
map ctrl+alt+q close_window

# Quitting
map alt+x>q quit
