[config]
[templates.blesh-colors]
input_path = "/home/mm/.config/matugen/templates/blesh-colors.sh"
output_path = "/home/mm/.config/blesh/colors.sh"

[templates.kitty-tabs]
input_path = "/home/mm/.config/matugen/templates/kitty-tabs.conf"
output_path = "/home/mm/.config/kitty/tabs.conf"

[templates.kitty-colors]
input_path = "/home/mm/.config/matugen/templates/kitty-colors.conf"
output_path = "/home/mm/.config/kitty/colors.conf"

[templates.starship]
input_path = "/home/mm/.config/matugen/templates/starship-palette.toml"
output_path = "/home/mm/.cache/matugen/starship-palette.toml"
post_hook = "cat /home/mm/.config/starship-base.toml /home/mm/.cache/matugen/starship-palette.toml > /home/mm/.config/starship.toml"

[templates.fzf]
input_path = "/home/mm/.config/matugen/templates/fzf-colors.conf"
output_path = "/home/mm/.cache/matugen/fzf-colors.conf"
post_hook = "cat /home/mm/.config/fzf/fzf-base.conf /home/mm/.cache/matugen/fzf-colors.conf > /home/mm/.config/fzf/fzf.conf"

[templates.niri-colors]
input_path = "/home/mm/.config/matugen/templates/niri-colors.kdl"
output_path = "/home/mm/.config/niri/colors.kdl"

